name: "main: Trigger Webpage Build"
on:
  push:
    branches:
      - deploy
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch sekai-viewer
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GITHUB_TOKEN }}
          repository: Sekai-World/sekai-viewer
          event-type: new-translation
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
